### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by MarkBasedow** [riquedev/DjangoLetterAvatar#1]
Error if name contains single quotes or other non alphanumeric characters.

**Comment by riquedev** [comment]
> Error if name contains single quotes or other non alphanumeric characters.


I apologize for the long wait.
I did some tests and didn't notice any more errors, however, if it happens again you can notify me here.
I'll keep the issue open in case it happens again.

**Comment by jintae123** [comment]
When kwargs is korean, TypeError Error occurs. ( example : kwargs = {'name': '세종대왕'} )
I resolved issue at [file](https://github.com/riquedev/django-initials-avatar/blob/master/django_initials_avatar/templatetags/initials_avatar.py)

as is : return f"%s?{urlencode(kwargs)}" % reverse('initials-avatar-svg')
to be : return f"{reverse('initials-avatar-svg')}?{urlencode(kwargs)}"

**Comment by riquedev** [comment]
> When kwargs is korean, TypeError Error occurs. ( example : kwargs = {'name': '세종대왕'} ) I resolved issue at [file](https://github.com/riquedev/django-initials-avatar/blob/master/django_initials_avatar/templatetags/initials_avatar.py)
> 
> as is : return f"%s?{urlencode(kwargs)}" % reverse('initials-avatar-svg') to be : return f"{reverse('initials-avatar-svg')}?{urlencode(kwargs)}"


Hello, I added a new test to check if the error will still occur after the modification, I'm not sure if it really is 100% solved.
If you can check in your environment and let me know if everything went well, I would be very grateful.
Thanks.

Here are the files that were changed:
https://github.com/riquedev/django-initials-avatar/blob/0.0.6/tests/test_avatar_render.py
https://github.com/riquedev/django-initials-avatar/blob/master/django_initials_avatar/templatetags/initials_avatar.py
https://github.com/riquedev/django-initials-avatar/blob/0.0.6/tests/data/issue_1.txt

**Comment by jintae123** [comment]
It works perfectly with korean.
Thanks you very mush!
