### ISSUE TITLE
Use template variabel in template tag

### ISSUE THREAD

**Issue by askurashev** [riquedev/DjangoLetterAvatar#2]
Hello.

How I insert, for example, account name in template tag:
`{% render_initials_avatar "{{ user.account.name }}" %}`

**Comment by Delvio** [comment]
how was this resolved?

**Comment by riquedev** [comment]
> how was this resolved?
Hello, sorry for the delay in responding to you.

You can simply do:
```django
{% render_initials_avatar user.account.name %}
```
